---
name: Bug report
description: Create a report to help us improve.
body:
  - type: markdown
    attributes:
      value: |
        Thank you for opening a bug report for Perses Helm Charts.

        Please do *NOT* ask support questions in Github issues.

        If your issue is not a feature request or bug report use [Discussions](https://github.com/perses/perses/discussions).
  - type: dropdown
    attributes:
      label: Chart
      description: Which chart is affected?
      options:
        - perses
        - perses-operator
    validations:
      required: true
  - type: textarea
    attributes:
      label: What did you do?
      description: Please provide steps for us to reproduce this issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What did you expect to see?
  - type: textarea
    attributes:
      label: What did you see instead? Under which circumstances?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    attributes:
      label: Chart version
      description: Output of `helm list` or the chart version you installed.
      placeholder: e.g. 0.1.0
  - type: input
    attributes:
      label: Kubernetes version
      description: Output of `kubectl version --short`.
      placeholder: e.g. v1.31.0
  - type: input
    attributes:
      label: Helm version
      description: Output of `helm version --short`.
      placeholder: e.g. v3.17.1
  - type: textarea
    attributes:
      label: Values used
      description: Insert the values overrides you used (helm install --set or values file). Don't forget to remove secrets.
      render: yaml
  - type: textarea
    attributes:
      label: Logs
      description: Insert relevant pod logs or Helm output here.
      render: text
