---
name: Feature request
description: Suggest an idea for this project.
body:
  - type: markdown
    attributes:
      value: |
        Thank you for opening a feature request for Perses Helm Charts.

        Please do *NOT* ask support questions in Github issues.

        If your issue is not a feature request or bug report use [Discussions](https://github.com/perses/perses/discussions).
  - type: dropdown
    attributes:
      label: Chart
      description: Which chart does this relate to?
      options:
        - perses
        - perses-operator
        - new chart
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposal
      description: Use case. Why is this important?
    validations:
      required: true
