name: "Setup environment"
description: "Setup GO or NPM environment"
inputs:
  enable_go:
    description: Whether to enable go specific features, such as caching.
    default: "false"
  enable_npm:
    description: Whether to enable npm specific features, such as caching.
    default: "false"
runs:
  using: composite
  steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.x
    - uses: actions/cache@v3.0.8
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
