name: Setup
description: sets up helm lint and testing environment
inputs:
  create-kind-cluster:
    description: "Whether or not to create a kind cluster during setup"
    required: true
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v4

    - uses: actions/setup-python@v6
      with:
        python-version: "3.x"
        check-latest: true

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.7.0

    - name: Create kind cluster
      uses: helm/kind-action@v1.12.0
      if: ${{ inputs.create-kind-cluster == 'true' }}
      with:
        node_image: kindest/node:v1.28.0
