name: lint and test

on:
  pull_request:
    paths:
      - "charts/**"
    branches:
      - main

jobs:
  helm-lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: load env
        run: cat .github/env >> $GITHUB_ENV

      - name: setup helm lint requirements
        uses: ./.github/actions/setup_helmlint
        with:
          create-kind-cluster: "true"
          kind-version: ${{ env.kind-version }}
          kind-image: ${{ env.kind-image }}

      - uses: perses/github-actions@v0.11.0
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_go: true

      # perses-operator chart requires cert-manager for webhook and metrics TLS certificates
      - name: install cert-manager
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/${{ env.cert-manager-version }}/cert-manager.yaml
          kubectl wait --for=condition=Available deployment --all -n cert-manager --timeout=120s

      - name: run chart-testing (install)
        run: ct install --all
      - name: install mdox
        run: go install github.com/bwplotka/mdox@latest

      - name: run chart README lint
        run: make update-helm-readme && make checkdocs
